### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by DrkMatr1984** [DailyStruggle/Glide#2]
Got this NPE today when I first joined. 

https://pastebin.com/JJULj8t1

Guess just do a quick check for null in case the player has not fully loaded or something.

**Comment by DailyStruggle** [comment]
the map is initialized in the static scope, so this is an unusual error. 

![image](https://user-images.githubusercontent.com/28832622/134448257-06b4195b-ba02-4307-b96b-36bc56d98a81.png)


Intellij even gives me a warning if I add a null check 

![image](https://user-images.githubusercontent.com/28832622/134448147-918612df-9e13-4a93-bdbf-c9ab505d43b6.png)

it does take try/catch without crying about it, so lets try that

**Comment by DrkMatr1984** [comment]
Yeah, it happened infrequently. I'll update and let you know if I see it again. I've had weird errors occasionally from other plugins messing with other plugins since upgrading to Java 16 and 1.17 recently.
