### ISSUE TITLE
Incompatibilities with RealisticSwimming, Elytra, and Survival Mechanics, possibly others

### ISSUE THREAD

**Issue by DrkMatr1984** [DailyStruggle/Glide#4]
I noticed some incompatibilities with other plugins that use player.setGliding() to do things. Would you mind if I put a pull request in over the next few days to provide compatibility with SurvivalMechanics? I am familiar with [RealisticSwimming's](https://www.spigotmc.org/resources/realistic-swimming.23082/) and [Elytra's](https://www.spigotmc.org/resources/elytra.19284/) codes and already know how I can fix this (I'll put pull requests into their devs to handle it on their end), and I own a copy of [SurvivalMechanics](https://www.spigotmc.org/resources/%E2%96%91-survivalmechanics-%E2%96%91-1-9-x-1-17-x-%E2%96%91.26156/) and they have API, so I'm sure I can figure it out and send you a PR for SurvivalMechanics compatibility.
Thanks for your hard work!

**Comment by DrkMatr1984** [comment]
Oh, also, I thought for in the future in case someone developing a plugin wanted to provide simple compatibility, you could do a `FixedMetadataValue m = new FixedMetadataValue(plugin, null);
            player.setMetadata("gliding", m);`
 Then other plugins could just check 
 `player.hasMetadata("gliding")`
 to make sure they're not gliding using your plugin before doing something.

**Comment by DrkMatr1984** [comment]
Actually, issues with SurvivalMechanics were not your fault, there are no conflicts with Elytra so that's good, and I haven't tested RealisticSwimming but will let you know shortly lol.

**Comment by DailyStruggle** [comment]
this plugin shouldn't auto-activate if a player is flying, gliding, or swimming.

https://github.com/DailyStruggle/Glide/blob/main/src/main/java/io/github/dailystruggle/glide/Listeners/OnFall.java#L25-L29

the command, on the other hand, should force a gliding state.

**Comment by DrkMatr1984** [comment]
Yep, you were right. It was a bug with another plugin. My bad. Your code is solid! I assumed you were checking player.isGliding(). 🤦‍♂️
